const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
document.body.classList.add('intro-lock');
const intro=$('#intro'), introVideo=$('#introVideo'), revealMask=$('#pageReveal'), skip=$('#skipIntro');
let introDone=false;
function enterSite(){if(introDone)return;introDone=true;revealMask.classList.add('open');intro.classList.add('exit');document.body.classList.remove('intro-lock');setTimeout(()=>{intro.style.display='none';revealMask.style.display='none'},1350)}
skip?.addEventListener('click',enterSite);introVideo?.addEventListener('timeupdate',()=>{if(introVideo.currentTime>8.55)enterSite()});introVideo?.addEventListener('ended',enterSite);setTimeout(enterSite,11000);
const nav=$('#nav'),progress=$('#progress');function onScroll(){nav?.classList.toggle('scrolled',scrollY>30);const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.transform=`scaleX(${max?scrollY/max:0})`}addEventListener('scroll',onScroll,{passive:true});onScroll();
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');$$('video',e.target).forEach(v=>{if(v.muted)v.play().catch(()=>{})})}else{$$('video',e.target).forEach(v=>{if(v.muted&&!e.target.classList.contains('hero'))v.pause()})}}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el));
const menuBtn=$('#menuBtn'),mobile=$('#mobileMenu');menuBtn?.addEventListener('click',()=>mobile.classList.toggle('open'));$$('a',mobile).forEach(a=>a.addEventListener('click',()=>mobile.classList.remove('open')));
const modal=$('#filmModal'),modalVideo=$('#modalVideo');$$('[data-film]').forEach(b=>b.addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');modalVideo.currentTime=0;modalVideo.play().catch(()=>{})}));function closeFilm(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');modalVideo.pause()}$('#closeFilm')?.addEventListener('click',closeFilm);modal?.addEventListener('click',e=>{if(e.target===modal)closeFilm()});addEventListener('keydown',e=>{if(e.key==='Escape')closeFilm()});
const form=$('#enquiryForm');form?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const subject=encodeURIComponent(`Aravali Reserve Private Enquiry — ${d.get('name')||''}`);const body=encodeURIComponent(`Name: ${d.get('name')||''}\nEmail: ${d.get('email')||''}\nOrganisation / Event: ${d.get('organisation')||''}\n\nRequirement:\n${d.get('message')||''}`);location.href=`mailto:indiatryme@gmail.com?subject=${subject}&body=${body}`});
if(matchMedia('(pointer:fine)').matches){const hero=$('.hero'),art=$('.hero-art');hero?.addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*8,y=(e.clientY/innerHeight-.5)*5;if(art)art.style.transform=`scale(1.02) translate(${x}px,${y}px)`});hero?.addEventListener('pointerleave',()=>{if(art)art.style.transform=''})}